config/routes.rb
Rails.application.routes.draw do
  get 'chatroom', to: 'chat_room#index'
  post '/', to: 'sessions#create'
  post 'message', to: 'messages#create'
  delete 'logout', to: 'sessions#destroy'
  root 'sessions#new'
  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  validates :body, presence: true
  belongs_to :user
  # by default the order is ascending
  scope :custom_display, -> { order(:created_at).last(20) }
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 25 },
    uniqueness: { case_sensitive: false }

  has_many :messages, dependent: :destroy
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= session[:user_id] ? User.find(session[:user_id]) : nil
  end

  def logged_in?
    !!current_user
  end

  def require_user
    unless logged_in?
      flash[:negative] = 'You must be logged in to perform that action'
      redirect_to root_path
    end
  end
end

app/controllers/chat_room_controller.rb
class ChatRoomController < ApplicationController
  before_action :require_user

  def index
    @messages = Message.custom_display
    @message = Message.new
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user

  def create
    message = current_user.messages.build(message_params)

    respond_to do |format|
      if message.save
        ActionCable.server.broadcast 'chat_room_channel',
          message: render_message(message)

        format.js
      else
        flash.now[:negative] = 'Message not sent'
      end
    end
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def render_message(message)
    render_to_string partial: 'message', object: message
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :already_logged?, only: [:new, :create]
  before_action :require_user, only: :destroy

  def new; end

  def create
    user = User.find_by(name: session_params[:name])

    if user && user.authenticate(session_params[:password])
      flash[:info] = 'You are logged in'
      session[:user_id] = user.id
      redirect_to chatroom_url
    else
      flash.now[:negative] = 'Wrong credentials'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:info] = 'Session terminated'
    redirect_to root_url
  end

  private

  def session_params
    params.require(:session).permit(:name, :password)
  end

  def already_logged?
    if logged_in?
      flash[:warning] = 'You are already logged in'
      redirect_to chatroom_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_room_helper.rb
module ChatRoomHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/chat_room/_feed.html.erb
<div class="content" id="messages-wrapper">
  <div class="ui feed" id="messages-box">
    <%= render @messages %>
  </div>
</div>

<div class="extra content">
  <%= form_for(@message, html: { class: 'ui reply form', role: 'form' },
    url: message_path, remote: true) do |f| %>
    <div class="field">
      <div class="ui right icon input">
        <%= f.text_field :body, placeholder: 'Enter a message...' %>
        <%= f.button '', class: 'send-message' %>
        <i class="bordered inverted orange edit icon"></i>
      </div>
    </div>
  <% end %>
</div>

app/views/chat_room/_vertical_menu.html.erb
<div class="content container">
  <div class="ui inverted vertical menu fluid container">
    <a class="active item">
      Home
    </a>
    <a class="item">
      Messages
    </a>
    <a class="item">
      Friends
    </a>
  </div>
</div>

app/views/chat_room/home.html.erb
<h2 class="ui center aligned medium icon header">
  <i class="circular orange coffee icon"></i>
  Say something
</h2>

<div class="ui two column grid">
  <div class="twelve wide column">
    <div class="ui fluid raised card chatbox">
      <%= render 'feed' %>
    </div>
  </div>

  <div class="four wide column">
    <div class="ui fluid raised card chatbox">
      <%= render 'vertical_menu' %>
    </div>
  </div>
</div>

app/views/chat_room/index.html.erb
<h2 class="ui center aligned medium icon header">
  <i class="circular orange coffee icon"></i>
  Say something
</h2>

<div class="ui two stackable column grid">
  <div class="twelve wide computer sixteen wide mobile column">
    <div class="ui fluid raised card chatbox">
      <%= render 'feed' %>
    </div>
  </div>

  <div class="four wide computer sixteen wide mobile column">
    <div class="ui fluid raised card chatbox">
      <%= render 'vertical_menu' %>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% if flash.any? %>
  <div class="ui grid">
    <% flash.each do |type, msg| %>
      <div class="column">
        <div class="ui <%= type %> message">
          <i class="close icon"></i>
          <div class="header">
            <%= msg %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="ui small inverted menu">
  <div class="ui container">
    <%= link_to 'Chatroom', chatroom_path, class: 'item'%>
    <div class="right menu">
      <% if logged_in? %>
        <div class="ui dropdown item">
          Account <i class="dropdown icon"></i>
          <div class="menu">
            <%= link_to 'Log out', logout_path, method: :delete, class: 'item' %>
          </div>
        </div>
      <% else %>
        <%= link_to 'Log in', root_path, class: 'item' %>
        <%= link_to 'Sign up', '#', class: 'ui primary disabled button' %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>

    <div class="ui container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
      <em><%= message.user.name %></em>:
      <%= message.body %>
    </div>
  </div>
</div>

app/views/messages/create.js.erb
document.getElementById('message_body').value = '';